import os
import math
import torch
import warnings

import torch.nn as nn

from einops import rearrange
from .net_utils import DWT_2D, IDWT_2D

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            'mean is more than 2 std from [a, b] in nn.init.trunc_normal_. '
            'The distribution of values may be incorrect.',
            stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        low = norm_cdf((a - mean) / std)
        up = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [low, up], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * low - 1, 2 * up - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution.

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py

    The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value

    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

import torch
import torch.nn as nn

class Task_Specific_Modulator(nn.Module):
    def __init__(self, expert_dim=5, num_experts=4, expand=512):
        super(Task_Specific_Modulator, self).__init__()
        self.gating_network = nn.Sequential(
            nn.Linear(expert_dim, expand),
            nn.Linear(expand, 2*num_experts)
        )

        self.weights1 = nn.Softmax(dim=-1)
        self.weights2 = nn.Softmax(dim=-1)

    def forward(self, prompts):
        prompts_weights = self.gating_network(prompts)


        weights1, weights2 = prompts_weights.chunk(2, -1)
        weights1 = self.weights1(weights1)
        weights2 = self.weights2(weights2)

        return weights1.unsqueeze(-1).unsqueeze(-1), weights2.unsqueeze(-1).unsqueeze(-1)

class DRMLP(nn.Module):
    def __init__(self, dim, hidden_dim, num_experts, expert_dim=5, deploy=False):
        super(DRMLP, self).__init__()
        self.num_experts = num_experts
        self.hidden_dim = hidden_dim
        self.dim = dim
        self.deploy = deploy
        self.TSM = Task_Specific_Modulator(expert_dim, num_experts)
        self.gelu_linear_groups = nn.GELU()
   
        if deploy:
            self.linear1 = nn.Linear(dim, hidden_dim)
            self.linear2 = nn.Linear(hidden_dim, dim)
        else:
            self.linear1_experts = nn.ModuleList([nn.Linear(dim, hidden_dim) for _ in range(num_experts)])
            self.linear2_experts = nn.ModuleList([nn.Linear(hidden_dim, dim) for _ in range(num_experts)])



    def forward(self, x, prompts):  
        b, l, _ = x.shape

        if self.deploy:
            weighted_output = self.linear2(self.gelu_linear_groups(self.linear1(x)))
        else:
            weights1, weights2 = self.TSM(prompts)

            weighted_output = torch.zeros((b,l,self.hidden_dim), device=x.device)
    
            for i in range(self.num_experts):
                weighted_output += self.linear1_experts[i](x) * weights1[:, i]

            x = self.gelu_linear_groups(weighted_output)

            weighted_output = torch.zeros((b,l,self.dim), device=x.device)
            for i in range(self.num_experts):
                weighted_output += self.linear2_experts[i](x) * weights2[:, i]
        
        return weighted_output

    def switch_to_deploy(self, task_prompt):
        if self.deploy:
            return
    
        self.deploy = True
        weights1_score, weights2_score = self.TSM(task_prompt)

        weights1, bias1 = self.linear1_experts[0].weight * weights1_score[:, 0].squeeze(-1).squeeze(-1), self.linear1_experts[0].bias * weights1_score[:, 0].squeeze(-1).squeeze(-1)
        weights2, bias2 = self.linear2_experts[0].weight * weights2_score[:, 0].squeeze(-1).squeeze(-1), self.linear2_experts[0].bias * weights2_score[:, 0].squeeze(-1).squeeze(-1)



        for i in range(1,self.num_experts):
            weights1.data += self.linear1_experts[i].weight.data * weights1_score[:, i].squeeze(-1).squeeze(-1)
            bias1.data += self.linear1_experts[i].bias.data * weights1_score[:, i].squeeze(-1).squeeze(-1)
            weights2.data += self.linear2_experts[i].weight.data * weights2_score[:, i].squeeze(-1).squeeze(-1)
            bias2.data += self.linear2_experts[i].bias.data * weights2_score[:, i].squeeze(-1).squeeze(-1)

        self.linear1 = nn.Linear(self.dim, self.hidden_dim)
        self.linear2 = nn.Linear(self.hidden_dim, self.dim)

        self.linear1.weight.data = weights1
        self.linear1.bias.data = bias1

        self.linear2.weight.data = weights2
        self.linear2.bias.data = bias2


        for para in self.parameters():
            para.detach_()
            

        self.__delattr__('linear1_experts')
        self.__delattr__('linear2_experts')
        self.__delattr__('TSM')


class WindowAttention(nn.Module):
    r""" Window based multi-head self attention (W-MSA) module with relative position bias.
    It supports both of shifted and non-shifted window.

    Args:
        dim (int): Number of input channels.
        window_size (tuple[int]): The height and width of the window.
        num_heads (int): Number of attention heads.
        qkv_bias (bool, optional):  If True, add a learnable bias to query, key, value. Default: True
        qk_scale (float | None, optional): Override default qk scale of head_dim ** -0.5 if set
        attn_drop (float, optional): Dropout ratio of attention weight. Default: 0.0
        proj_drop (float, optional): Dropout ratio of output. Default: 0.0
    """

    def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None, attn_drop=0., proj_drop=0.):

        super().__init__()
        self.dim = dim
        self.window_size = window_size  # Wh, Ww
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        # define a parameter table of relative position bias
        self.relative_position_bias_table = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1), num_heads))  # 2*Wh-1 * 2*Ww-1, nH

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)

        self.proj_drop = nn.Dropout(proj_drop)

        trunc_normal_(self.relative_position_bias_table, std=.02)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x, rpi, mask=None):
        """
        Args:
            x: input features with shape of (num_windows*B, N, C)
            mask: (0/-inf) mask with shape of (num_windows, Wh*Ww, Wh*Ww) or None
        """
        B_, N, C = x.shape
        qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]  # make torchscript happy (cannot use tensor as tuple)

        q = q * self.scale
        attn = (q @ k.transpose(-2, -1))

        relative_position_bias = self.relative_position_bias_table[rpi.view(-1)].view(
            self.window_size[0] * self.window_size[1], self.window_size[0] * self.window_size[1], -1)  # Wh*Ww,Wh*Ww,nH
        relative_position_bias = relative_position_bias.permute(2, 0, 1).contiguous()  # nH, Wh*Ww, Wh*Ww
        attn = attn + relative_position_bias.unsqueeze(0)

        if mask is not None:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.num_heads, N, N) + mask.unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.num_heads, N, N)
            attn = self.softmax(attn)
        else:
            attn = self.softmax(attn)

        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x

def window_partition(x, window_size):
    """
    Args:
        x: (B, H, W, C)
        window_size (int): window size

    Returns:
        windows: (num_windows*B, window_size, window_size, C)
    """
    B, H, W, C = x.shape
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
    windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, C)
    return windows


def window_reverse(windows, window_size, H, W):
    """
    Args:
        windows: (num_windows*B, window_size, window_size, C)
        window_size (int): Window size
        H (int): Height of image
        W (int): Width of image

    Returns:
        x: (B, H, W, C)
    """
    B = int(windows.shape[0] / (H * W / window_size / window_size))
    x = windows.view(B, H // window_size, W // window_size, window_size, window_size, -1)
    x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, -1)
    return x


class DRB(nn.Module):
    def __init__(self, hidden_size, num_heads, mlp_ratio=4.0, shift_size=4, window_size=8, input_size=32, num_experts=8, expert_dim=5):
        super().__init__()
        self.norm1 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
        self.shift_size = shift_size
        self.window_size = window_size
        self.input_resolution = (input_size,input_size)

        self.attn = WindowAttention(
            hidden_size, window_size=(self.window_size, self.window_size), num_heads=num_heads,
            qkv_bias=True)

        self.norm2 = nn.LayerNorm(hidden_size, elementwise_affine=False, eps=1e-6)
    
        self.dm_mlp = DRMLP(dim=hidden_size, hidden_dim=int(hidden_size*mlp_ratio), num_experts=num_experts, expert_dim=expert_dim)

    def forward(self, x, prompts=None, rpi=None, mask=None):
        B, C, h, w = x.shape
        x = rearrange(x, 'b c h w -> b (h w) c')
        shortcut = x
        x = self.norm1(x)

        x = x.view(B, h, w, C)

        # cyclic shift
        if self.shift_size > 0:
            shifted_x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), dims=(1, 2))
            attn_mask = mask
        else:
            shifted_x = x
            attn_mask = None

        # partition windows
        x_windows = window_partition(shifted_x, self.window_size)  # nW*B, window_size, window_size, C
        x_windows = x_windows.view(-1, self.window_size * self.window_size, C)  # nW*B, window_size*window_size, C

        # W-MSA/SW-MSA (to be compatible for testing on images whose shapes are the multiple of window size
 
        attn_windows = self.attn(x_windows, rpi, attn_mask)

        # merge windows
        attn_windows = attn_windows.view(-1, self.window_size, self.window_size, C)
        shifted_x = window_reverse(attn_windows, self.window_size, h, w)  # B H' W' C

        # reverse cyclic shift
        if self.shift_size > 0:
            x = torch.roll(shifted_x, shifts=(self.shift_size, self.shift_size), dims=(1, 2))
        else:
            x = shifted_x

        x = x.view(B, h * w, C)
        x = shortcut + x
        x = x + self.dm_mlp(self.norm2(x), prompts)
        x = rearrange(x, 'b (h w) c -> b c h w', h=h, w=w)
        return x
    
class Downsample(nn.Module):
    def __init__(self, n_feat):
        super(Downsample, self).__init__()
        self.body = nn.Conv2d(n_feat, n_feat, kernel_size=3, stride=1, padding=1, bias=False)


    def forward(self, x, dwt):
        return dwt(self.body(x))
    
class Upsample(nn.Module):
    def __init__(self, n_feat):
        super(Upsample, self).__init__()

        self.body = nn.Conv2d(n_feat, n_feat, kernel_size=3, stride=1, padding=1, bias=False)

    def forward(self, x, idwt):
        return idwt(self.body(x))
    
class CWTE(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        self.hidden_size = hidden_size
        self.dwt = DWT_2D(wave='haar')
        
        self.down1_2 = Downsample(hidden_size) ## From Level 1 to Level 2
        
        self.down2_3 = Downsample(int(hidden_size)) ## From Level 2 to Level 3

        self.down3_4 = Downsample(int(hidden_size)) ## From Level 3 to Level 4

    def forward(self, x):

        x_wavel1_2 = self.down1_2(x, self.dwt)

        x_wavel2_3 = self.down2_3(x_wavel1_2[:, :self.hidden_size], self.dwt)

        x_wavel3_4 = self.down3_4(x_wavel2_3[:, :self.hidden_size], self.dwt)

        return x_wavel1_2, x_wavel2_3, x_wavel3_4
    
class DRNet(nn.Module):
    def __init__(
        self,
        input_size=32,
        in_channels=3,
        hidden_size=48,
        num_blocks=[2,3,3,4],
        heads=[1,2,4,8],
        mlp_ratio=2.0,
        num_experts=3,
        window_size=8,
        expert_dim=5
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = in_channels
        self.hidden_dim = hidden_size
        self.window_size = window_size
        self.shift_size = window_size // 2

        self.conv_first = nn.Conv2d(self.in_channels, self.hidden_dim, 3, 1, 1)

        self.feature_enhance = nn.Sequential(
            *[
                DRB(
                    hidden_size, heads[0], 
                    mlp_ratio,
                    input_size=input_size,
                    shift_size=0 if (i % 2 == 0) else window_size // 2,
                    window_size = window_size,
                    num_experts=num_experts, 
                    expert_dim=expert_dim
                ) for i in range(num_blocks[0])
            ]
        )


        # ############################  DWT Auxiliary Encoder   ##########################
        self.encoder = CWTE(self.hidden_dim)
        self.idwt = IDWT_2D(wave='haar')


        self.decoder_level3 = nn.ModuleList(
            [
                DRB(
                    hidden_size*4, heads[3], 
                    mlp_ratio,
                    input_size=input_size,
                    shift_size=0 if (i % 2 == 0) else window_size // 2,
                    window_size = window_size,
                    num_experts=num_experts, 
                    expert_dim=expert_dim
                ) for i in range(num_blocks[3])
            ]
        )
        
        self.up4_3 = Upsample(int(hidden_size*4)) ## From Level 4 to Level 3

        self.decoder_level2 = nn.ModuleList(
            [
                DRB(
                    hidden_size*4, heads[2], 
                    mlp_ratio,
                    input_size=input_size,
                    shift_size=0 if (i % 2 == 0) else window_size // 2,
                    window_size = window_size,
                    num_experts=num_experts, 
                    expert_dim=expert_dim
                ) for i in range(num_blocks[2])
            ]
        )


        self.up3_2 = Upsample(int(hidden_size*4)) ## From Level 3 to Level 2

        self.decoder_level1 = nn.ModuleList(
            [
                DRB(
                    int(hidden_size*4), 
                    heads[1], 
                    mlp_ratio, 
                    input_size=input_size, 
                    shift_size=0 if (i % 2 == 0) else window_size // 2, 
                    window_size = window_size,
                    num_experts=num_experts, 
                    expert_dim=expert_dim, 
                ) for i in range(num_blocks[1])
            ]
        )
        
        self.up2_1 = Upsample(int(hidden_size*4))  ## From Level 2 to Level 1  (NO 1x1 conv to reduce channels)

        self.refine = nn.ModuleList(
            [
                DRB(
                    int(hidden_size), 
                    heads[0], 
                    mlp_ratio, 
                    input_size=input_size, 
                    shift_size=0 if (i % 2 == 0) else window_size // 2, 
                    window_size = window_size,
                    num_experts=num_experts, 
                    expert_dim=expert_dim
                ) for i in range(num_blocks[0])
            ]
        )


        self.conv_after_body = nn.Conv2d(self.hidden_dim, self.hidden_dim, 3, 1, 1)

        self.conv_fnl = nn.Conv2d(self.hidden_dim, self.out_channels, 3, 1, 1)

        self.concat_fuse = nn.Conv2d(self.hidden_dim*2, self.hidden_dim, 1)

        self.initialize_weights()

    def calculate_rpi_sa(self):
        # calculate relative position index for SA
        coords_h = torch.arange(self.window_size)
        coords_w = torch.arange(self.window_size)
        coords = torch.stack(torch.meshgrid([coords_h, coords_w]))  # 2, Wh, Ww
        coords_flatten = torch.flatten(coords, 1)  # 2, Wh*Ww
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 2, Wh*Ww, Wh*Ww
        relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wh*Ww, Wh*Ww, 2
        relative_coords[:, :, 0] += self.window_size - 1  # shift to start from 0
        relative_coords[:, :, 1] += self.window_size - 1
        relative_coords[:, :, 0] *= 2 * self.window_size - 1
        relative_position_index = relative_coords.sum(-1)  # Wh*Ww, Wh*Ww
        return relative_position_index

    def calculate_mask(self, x_size):
        # calculate attention mask for SW-MSA
        h, w = x_size
        img_mask = torch.zeros((1, h, w, 1))  # 1 h w 1
        h_slices = (slice(0, -self.window_size), slice(-self.window_size,
                                                       -self.shift_size), slice(-self.shift_size, None))
        w_slices = (slice(0, -self.window_size), slice(-self.window_size,
                                                       -self.shift_size), slice(-self.shift_size, None))
        cnt = 0
        for h in h_slices:
            for w in w_slices:
                img_mask[:, h, w, :] = cnt
                cnt += 1

        mask_windows = window_partition(img_mask, self.window_size)  # nw, window_size, window_size, 1
        mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
        attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))

        return attn_mask

    def initialize_weights(self):
        def _basic_init(module):
            if isinstance(module, nn.Linear):
                torch.nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.constant_(module.bias, 0)
            if isinstance(module, nn.Conv2d):
                nn.init.normal_(module.weight.data, mean=0.0, std=math.sqrt(2/(module.out_channels*module.weight.data[0][0].numel())))
                if module.bias is not None:
                    nn.init.zeros_(module.bias.data)
        self.apply(_basic_init)


    def forward(self, x, prompts=None):
        attn_mask_level1 = self.calculate_mask((x.shape[2], x.shape[3])).to(x.device)
        attn_mask_level2 = self.calculate_mask((x.shape[2]//2, x.shape[3]//2)).to(x.device)
        attn_mask_level3 = self.calculate_mask((x.shape[2]//2**2, x.shape[3]//2**2)).to(x.device)
        attn_mask_level4 = self.calculate_mask((x.shape[2]//2**3, x.shape[3]//2**3)).to(x.device)

        params = {'attn_mask': [attn_mask_level1, attn_mask_level2, attn_mask_level3, attn_mask_level4], 'rpi': self.calculate_rpi_sa()}

        shallow_feas = self.conv_first(x) 

        inp_enc_level1 = shallow_feas

        for layer in self.feature_enhance:
            inp_enc_level1 = layer(inp_enc_level1, prompts, params['rpi'], params['attn_mask'][0])  

        x_wavel1_2, x_wavel2_3, x_wavel3_4 = self.encoder(inp_enc_level1)   


        inp_enc_level4 = x_wavel3_4
        for layer in self.decoder_level3:
            inp_enc_level4 = layer(inp_enc_level4, prompts, params['rpi'], params['attn_mask'][3]) 



        inp_dec_level3 = self.up4_3(inp_enc_level4, self.idwt)
        inp_dec_level3 = torch.cat([inp_dec_level3, x_wavel2_3[:, self.hidden_dim:]], 1)

        for layer in self.decoder_level2:
            inp_dec_level3 = layer(inp_dec_level3, prompts, params['rpi'], params['attn_mask'][2])  

        inp_dec_level2 = self.up3_2(inp_dec_level3, self.idwt)
        inp_dec_level2 = torch.cat([inp_dec_level2, x_wavel1_2[:, self.hidden_dim:]], 1)

        for layer in self.decoder_level1:
            inp_dec_level2 = layer(inp_dec_level2, prompts, params['rpi'], params['attn_mask'][1])  

        inp_dec_level1 = self.up2_1(inp_dec_level2, self.idwt)
        inp_dec_level1 = torch.cat([inp_dec_level1, inp_enc_level1], 1)

        inp_dec_level1 = self.concat_fuse(inp_dec_level1)

        for layer in self.refine:
            inp_dec_level1 = layer(inp_dec_level1, prompts, params['rpi'], params['attn_mask'][0])  


        x = self.conv_after_body(inp_dec_level1) + shallow_feas 
        x = self.conv_fnl(x)
        return x

if __name__ == "__main__":
    import os
    os.environ['CUDA_VISIBLE_DEVICES'] = '5'
    model = DRNet(num_experts=4, expert_dim=5, hidden_size=48, mlp_ratio=2, num_blocks=[4,6,6,8]).cuda()
    height = 128
    width = 128
    inp = torch.rand((1,3,height,width)).cuda()
    lq = torch.rand((1,3,height,width)).cuda()
    y = torch.rand((1,5)).cuda()
    t = torch.randint(100,(1,)).cuda()
    out = model(inp, y)
    params = sum(map(lambda x: x.numel(), model.parameters()))
    print(params)